const cardsArr = [{
    img: './cards/card-0.jpg',
    value: 0,
    matched: false,
    flipped: false,
    rotate: 'inside',
},
{
    img: './cards/card-1.jpg',
    value: 1,
    matched: false,
    flipped: false,
    rotate: 'inside',
},
{
    img: './cards/card-2.jpg',
    value: 2,
    matched: false,
    flipped: false,
    rotate: 'inside',
},
{
    img: './Images/cards/card-3.jpg',
    value: 3,
    matched: false,
    flipped: false,
    rotate: 'inside',
},
{
    img: './Images/cards/card-4.jpg',
    value: 4,
    matched: false,
    flipped: false,
    rotate: 'inside',
},
{
    img: './Images/cards/card-5.jpg',
    value: 5,
    matched: false,
    flipped: false,
    rotate: 'inside',
},
{
    img: './Images/cards/card-6.jpg',
    value: 6,
    matched: false,
    flipped: false,
    rotate: 'inside',
},
{
    img: './Images/cards/card-7.jpg',
    value: 7,
    matched: false,
    flipped: false,
    rotate: 'inside',
},
{
    img: './Images/cards/card-8.jpg',
    value: 8,
    matched: false,
    flipped: false,
    rotate: 'inside',
},
{
    img: './Images/cards/card-9.jpg',
    value: 9,
    matched: false,
    flipped: false,
    rotate: 'inside',
},
{
    img: './Images/cards/card-10.jpg',
    value: 10,
    matched: false,
    flipped: false,
    rotate: 'inside',
},
{
    img: './Images/cards/card-11.jpg',
    value: 11,
    matched: false,
    flipped: false,
    rotate: 'inside',
},
];

export default cardsArr;
